### ISSUE TITLE
Error Information

### ISSUE THREAD

**Issue by H-Tung** [simgunz/anki21-addons_minimize-to-tray#10]
```
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19041
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-08-17 11:01:56

Caught exception:
Traceback (most recent call last):
  File "D:\Applications\Scoop\persist\anki\data\addons21\85158043\__init__.py", line 56, in onActivated
    self.showAll()
  File "D:\Applications\Scoop\persist\anki\data\addons21\85158043\__init__.py", line 74, in showAll
    self._showWindows(self.explicitlyHiddenWindows)
  File "D:\Applications\Scoop\persist\anki\data\addons21\85158043\__init__.py", line 91, in _showWindows
    if w.isMinimized() == Qt.WindowMinimized:
RuntimeError: wrapped C/C++ object of type CustomLabel has been deleted
```

**Comment by simgunz** [comment]
Can you test again with the latest update (version 2.0.0 of the addon) and Anki 23.10.1 Qt6?
